# version: "3.9"

services:
  nextjs:
    build:
      context: ./searcheable-catalog
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"

  golang:
    build:
      context: ./golang-service
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"

  python:
    build:
      context: ./python-service
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
